//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:38:17 PM BST 
//


package com.thomas.lundberg.jaxb_generated_objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse"
})
@XmlRootElement(name = "dict")
public class Dict {

    @XmlElements({
        @XmlElement(name = "key", type = Key.class),
        @XmlElement(name = "array", type = Array.class),
        @XmlElement(name = "data", type = Data.class),
        @XmlElement(name = "date", type = Date.class),
        @XmlElement(name = "dict", type = Dict.class),
        @XmlElement(name = "real", type = Real.class),
        @XmlElement(name = "integer", type = Integer.class),
        @XmlElement(name = "string", type = String.class),
        @XmlElement(name = "true", type = True.class),
        @XmlElement(name = "false", type = False.class)
    })
    protected List<Object> keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse;

    /**
     * Gets the value of the keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Key }
     * {@link Array }
     * {@link Data }
     * {@link Date }
     * {@link Dict }
     * {@link Real }
     * {@link Integer }
     * {@link String }
     * {@link True }
     * {@link False }
     * 
     * 
     */
    public List<Object> getKeyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse() {
        if (keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse == null) {
            keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse = new ArrayList<Object>();
        }
        return this.keyOrArrayOrDataOrDateOrDictOrRealOrIntegerOrStringOrTrueOrFalse;
    }

}
